service: micro-example-serverless

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless-admin
  region: us-west-2
  environment:
    SERVERLESS_REGION: ${opt:region, self:provider.region}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
